// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHVnpmx3iaMP7IGE_GNOIWlfiGhL2ZKo',
    appId: '1:770322332280:web:5598f90a72fad0d2f50b8d',
    messagingSenderId: '770322332280',
    projectId: 'fir-image-6275e',
    authDomain: 'fir-image-6275e.firebaseapp.com',
    storageBucket: 'fir-image-6275e.appspot.com',
    measurementId: 'G-ZJGPZJSM8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxxNnztJ2fuoav9agih0qAjvAO14EmVA',
    appId: '1:770322332280:android:1184e3ad02a0bbd1f50b8d',
    messagingSenderId: '770322332280',
    projectId: 'fir-image-6275e',
    storageBucket: 'fir-image-6275e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUw_usB15SbyPt4pBES8L4GfDBQHoA_oM',
    appId: '1:770322332280:ios:2faadbb8dd7f6cfdf50b8d',
    messagingSenderId: '770322332280',
    projectId: 'fir-image-6275e',
    storageBucket: 'fir-image-6275e.appspot.com',
    iosBundleId: 'com.example.firebaseImgae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUw_usB15SbyPt4pBES8L4GfDBQHoA_oM',
    appId: '1:770322332280:ios:375d0e8dd03d287af50b8d',
    messagingSenderId: '770322332280',
    projectId: 'fir-image-6275e',
    storageBucket: 'fir-image-6275e.appspot.com',
    iosBundleId: 'com.example.firebaseImgae.RunnerTests',
  );
}
